### ISSUE TITLE
Quelques idées pour la page ressources

### ISSUE THREAD

**Issue by noftaly** [Uneo7/Skript-MC#24]
- Je pense qu'il faudrait moins de padding entre les catégories (What's new, Highest Rated, Most Downloaded)
- Voir pouvoir les réduire ou les dérouler.
- Je pense qu'il faudrait aussi réduire la taille des aperçus pour en mettre plus dans une ligne (Maintenant 5,5, faudrait pouvoir en mettre genre 7).
- Après Most Downloaded (la dernière section de la page d'accueil), faudrait une section Toutes les ressources, ou la il y a une grille de toutes les ressources. Quelque chose comme ca :
![image](https://user-images.githubusercontent.com/34779161/51321061-113f7780-1a62-11e9-81e1-e095494439df.png)

**Comment by Uneo7** [comment]
Je sais pas si t'a pigé le concept. je vais **tout refaire**.

**Comment by noftaly** [comment]
Bah dans ces cas la cette issue est inutile, je pensais pas que t'allais tout refaire, je pensais que t'aller juste modifier le truc déjà existant !
Du coup je close, ca a plus de réel interêt. Si j'ai d'autres idées je referai une issue.
