### ISSUE TITLE
Mauvais lien copié (doc)

### ISSUE THREAD

**Issue by Angel-0** [Uneo7/Skript-MC#25]
Le bouton encadré en rouge sur le screen ci-dessous copie `/documentation/skript/evenements#on_drop` au lieu de `https://doc.skript-mc.fr/documentation/skript/evenements#on_drop`
![image](https://user-images.githubusercontent.com/30158363/51333307-bb78c880-1a7d-11e9-9fdf-c706ec6875d3.png)

**Comment by noftaly** [comment]
Nan c'est normal ça fait ça pour tous, c'est pour mettre des liens dans les articles.
Enfin il me semble

**Comment by Uneo7** [comment]
C'est bine ça. Ce bouton n'est visible que pour les contributeurs. **Il est très important de ne pas utiliser** les liens absolus (aka les liens en https://doc.skript.fr/...)/
