### ISSUE TITLE
Avis sur la coloration syntaxique

### ISSUE THREAD

**Issue by Olyno** [Uneo7/Skript-MC#28]
# Description

J'ai pu souligner quelques conflits avec la coloration syntaxique, voici une petite liste ci-dessous.
Ça reste mon avis mais il faudrait ajouter une couleur au mot "and" (``.{1,} (and) .{1,}`` où le groupe 1 est le mot ``and``) et les event-expressions (``\%event-(\w+)\%`` où le groupe 1 est le type de la valeur retourné (exemple: ``event-game`` sera un type ``game``))

![](https://i.imgur.com/8JLiKJR.png)

# Conflits:

![](https://i.imgur.com/WcVtd3U.png)

**Regex pour la date:** ``(at )?([2][0-3]|[0-1][0-9]\:[0-5][0-9])|(([0-2][0-9]|[3][0-1])\/([0][1-9]|[1][0-2])\/([0-2][0-9]{3}))|(([0-2][0-9]{3})\/([0][1-9]|[1][0-2])\/([0-2][0-9]|[3][0-1]))``

![](https://i.imgur.com/OfKOMiu.png)
![](https://i.imgur.com/82VHNS5.png)

**Pull request correspondante;** https://github.com/Uneo7/Skript-MC/pull/29

**Comment by Uneo7** [comment]
C'est merge
