### ISSUE TITLE
Dépendance des addons

### ISSUE THREAD

**Issue by Yghore** [Uneo7/Skript-MC#30]
rajouter une case "dépendance" a la création d'un addons sur la doc :smile:

**Comment by Uneo7** [comment]
Qui sert à quoi ? Détaille ta demande ...

**Comment by Olyno** [comment]
Certains addons peuvent avoir besoin d'un autre plugin (autre que skript) pour fonctionner ou avoir des fonctionnalités supplémentaires. Je pense qu'il s'agit de ça.

**Comment by noftaly** [comment]
Exemple : FacSk, qui a besoin d'un plugin Faction
FaweSk/Skematic : a besoin de WorldEdit

**Comment by WeeskyBDW** [comment]
Ajouté.

**Comment by Yghore** [comment]
Tu gères bg
