### ISSUE TITLE
Edition rapide d'article rapporté

### ISSUE THREAD

**Issue by CelestialKitsune** [Uneo7/Skript-MC#32]
Ajouter une édition rapide quelque part là 
![image](https://user-images.githubusercontent.com/30158363/51703691-4b3aeb80-2017-11e9-934a-7a80baf47cc7.png)

ou là

![image](https://user-images.githubusercontent.com/30158363/51703794-99e88580-2017-11e9-98cd-349d36361b0a.png)

**Comment by Yghore** [comment]
Je propose aussi un bouton pour supprimer le rapport depuis la page ici 
https://user-images.githubusercontent.com/30158363/51703691-4b3aeb80-2017-11e9-934a-7a80baf47cc7.png

**Comment by Olyno** [comment]
Et pour ma part je propos un bouton pour renvoyer à l'article qui a été signaler, nous évitant ainsi de chercher.

**Comment by WeeskyBDW** [comment]
les 3 boutons ont été ajoutés
