### ISSUE TITLE
Problème de doubles parenthèses

### ISSUE THREAD

**Issue by Rak-Kara** [Uneo7/Skript-MC#42]
quand dans la doc on essaye de mettre deux parenthèses ( " ) collés comme ça -> ""
et bien ça nous rend -> " "
avec un espace au milieu, ce qui est une faute pour skript, donc c'est assez contraignant pour la documentation
![Screenshot_514](https://user-images.githubusercontent.com/53531480/62487364-e5979b00-b7c1-11e9-8817-36e8983874c0.png)
----
Dans l'édition de la doc:
![Screenshot_515](https://user-images.githubusercontent.com/53531480/62487394-fd6f1f00-b7c1-11e9-89de-61fb8639ebd0.png)

**Comment by WeeskyBDW** [comment]
Fixé (Par Uneo je pense)
